#include "xparameters.h"

#define TIMERCLK XPAR_PSU_TTC_0_TTC_CLK_FREQ_HZ
#define SHELLCONFIG_BASE	XPAR_STATIC_SHELL_DFX_SLOT_MANAGER_SIHA_MANAGER_0_BASEADDR

//#define RM0_CONFIG	XPAR_RP_0_ACCELCONFIG_0_BASEADDR
//#define RM1_CONFIG	XPAR_RP_1_ACCELCONFIG_0_BASEADDR

#define RM0_CONFIG	XPAR_ACCELCONFIG_0_BASEADDR
#define RM1_CONFIG	XPAR_ACCELCONFIG_1_BASEADDR

//#define DMA_HLS_0_BASE 	XPAR_RP_0_RM_COMM_BOX_0_BASEADDR
//#define DMA_HLS_1_BASE 	XPAR_RP_1_RM_COMM_BOX_0_BASEADDR

#define DMA_HLS_0_BASE 	XPAR_RM_COMM_BOX_0_BASEADDR
#define DMA_HLS_1_BASE 	XPAR_RM_COMM_BOX_1_BASEADDR
