-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pp_pipeline_accel_Array2xfMat_64_0_2160_3840_1_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    imgInput_y_466_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    imgInput_y_466_full_n : IN STD_LOGIC;
    imgInput_y_466_write : OUT STD_LOGIC;
    srcPtr_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    srcPtr_empty_n : IN STD_LOGIC;
    srcPtr_read : OUT STD_LOGIC;
    dstMat_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    dstMat_1_empty_n : IN STD_LOGIC;
    dstMat_1_read : OUT STD_LOGIC;
    dstMat_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    dstMat_2_empty_n : IN STD_LOGIC;
    dstMat_2_read : OUT STD_LOGIC;
    stride_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    stride_empty_n : IN STD_LOGIC;
    stride_read : OUT STD_LOGIC;
    dstMat_1_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstMat_1_out_full_n : IN STD_LOGIC;
    dstMat_1_out_write : OUT STD_LOGIC;
    dstMat_2_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstMat_2_out_full_n : IN STD_LOGIC;
    dstMat_2_out_write : OUT STD_LOGIC );
end;


architecture behav of pp_pipeline_accel_Array2xfMat_64_0_2160_3840_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal srcPtr_blk_n : STD_LOGIC;
    signal dstMat_1_blk_n : STD_LOGIC;
    signal dstMat_2_blk_n : STD_LOGIC;
    signal stride_blk_n : STD_LOGIC;
    signal dstMat_1_out_blk_n : STD_LOGIC;
    signal dstMat_2_out_blk_n : STD_LOGIC;
    signal srcPtr_read_reg_106 : STD_LOGIC_VECTOR (63 downto 0);
    signal dstMat_1_read_reg_111 : STD_LOGIC_VECTOR (31 downto 0);
    signal dstMat_2_read_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal stride_read_reg_121 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_imgInput_y_466_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Axi2Mat_1_fu_90_imgInput_y_466_write : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_ap_start : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_ap_done : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_ap_ready : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_ap_idle : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_ap_continue : STD_LOGIC;
    signal grp_Axi2Mat_1_fu_90_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call16 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_sync_grp_Axi2Mat_1_fu_90_ap_ready : STD_LOGIC;
    signal ap_sync_grp_Axi2Mat_1_fu_90_ap_done : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_done : STD_LOGIC := '0';
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component pp_pipeline_accel_Axi2Mat_1 IS
    port (
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        imgInput_y_466_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        imgInput_y_466_full_n : IN STD_LOGIC;
        imgInput_y_466_write : OUT STD_LOGIC;
        din : IN STD_LOGIC_VECTOR (63 downto 0);
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        stride : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        din_ap_vld : IN STD_LOGIC;
        rows_ap_vld : IN STD_LOGIC;
        cols_ap_vld : IN STD_LOGIC;
        stride_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    grp_Axi2Mat_1_fu_90 : component pp_pipeline_accel_Axi2Mat_1
    port map (
        m_axi_gmem1_AWVALID => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_Axi2Mat_1_fu_90_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_Axi2Mat_1_fu_90_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => grp_Axi2Mat_1_fu_90_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_Axi2Mat_1_fu_90_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_Axi2Mat_1_fu_90_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_Axi2Mat_1_fu_90_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_Axi2Mat_1_fu_90_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY => grp_Axi2Mat_1_fu_90_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST => m_axi_gmem1_RLAST,
        m_axi_gmem1_RID => m_axi_gmem1_RID,
        m_axi_gmem1_RUSER => m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP => m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => grp_Axi2Mat_1_fu_90_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        imgInput_y_466_din => grp_Axi2Mat_1_fu_90_imgInput_y_466_din,
        imgInput_y_466_full_n => imgInput_y_466_full_n,
        imgInput_y_466_write => grp_Axi2Mat_1_fu_90_imgInput_y_466_write,
        din => srcPtr_read_reg_106,
        rows => dstMat_1_read_reg_111,
        cols => dstMat_2_read_reg_116,
        stride => stride_read_reg_121,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        din_ap_vld => ap_const_logic_1,
        rows_ap_vld => ap_const_logic_1,
        cols_ap_vld => ap_const_logic_1,
        stride_ap_vld => ap_const_logic_1,
        ap_start => grp_Axi2Mat_1_fu_90_ap_start,
        ap_done => grp_Axi2Mat_1_fu_90_ap_done,
        ap_ready => grp_Axi2Mat_1_fu_90_ap_ready,
        ap_idle => grp_Axi2Mat_1_fu_90_ap_idle,
        ap_continue => grp_Axi2Mat_1_fu_90_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_done <= ap_const_logic_0;
                elsif ((grp_Axi2Mat_1_fu_90_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_ready <= ap_const_logic_0;
                elsif ((grp_Axi2Mat_1_fu_90_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Axi2Mat_1_fu_90_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Axi2Mat_1_fu_90_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_Axi2Mat_1_fu_90_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    grp_Axi2Mat_1_fu_90_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Axi2Mat_1_fu_90_ap_ready = ap_const_logic_1)) then 
                    grp_Axi2Mat_1_fu_90_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                dstMat_1_read_reg_111 <= dstMat_1_dout;
                dstMat_2_read_reg_116 <= dstMat_2_dout;
                srcPtr_read_reg_106 <= srcPtr_dout;
                stride_read_reg_121 <= stride_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call16_assign_proc : process(real_start, ap_done_reg, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
                ap_block_state1_ignore_call16 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(ap_sync_grp_Axi2Mat_1_fu_90_ap_ready, ap_sync_grp_Axi2Mat_1_fu_90_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_sync_grp_Axi2Mat_1_fu_90_ap_ready and ap_sync_grp_Axi2Mat_1_fu_90_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    ap_sync_grp_Axi2Mat_1_fu_90_ap_done <= (grp_Axi2Mat_1_fu_90_ap_done or ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_done);
    ap_sync_grp_Axi2Mat_1_fu_90_ap_ready <= (grp_Axi2Mat_1_fu_90_ap_ready or ap_sync_reg_grp_Axi2Mat_1_fu_90_ap_ready);

    dstMat_1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_1_blk_n <= dstMat_1_empty_n;
        else 
            dstMat_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dstMat_1_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_1_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_1_out_blk_n <= dstMat_1_out_full_n;
        else 
            dstMat_1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstMat_1_out_din <= dstMat_1_dout;

    dstMat_1_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_1_out_write <= ap_const_logic_1;
        else 
            dstMat_1_out_write <= ap_const_logic_0;
        end if; 
    end process;


    dstMat_1_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_1_read <= ap_const_logic_1;
        else 
            dstMat_1_read <= ap_const_logic_0;
        end if; 
    end process;


    dstMat_2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_2_blk_n <= dstMat_2_empty_n;
        else 
            dstMat_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dstMat_2_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_2_out_blk_n <= dstMat_2_out_full_n;
        else 
            dstMat_2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstMat_2_out_din <= dstMat_2_dout;

    dstMat_2_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_2_out_write <= ap_const_logic_1;
        else 
            dstMat_2_out_write <= ap_const_logic_0;
        end if; 
    end process;


    dstMat_2_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_2_read <= ap_const_logic_1;
        else 
            dstMat_2_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_Axi2Mat_1_fu_90_ap_continue_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_Axi2Mat_1_fu_90_ap_continue <= ap_const_logic_1;
        else 
            grp_Axi2Mat_1_fu_90_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_Axi2Mat_1_fu_90_ap_start <= grp_Axi2Mat_1_fu_90_ap_start_reg;
    imgInput_y_466_din <= grp_Axi2Mat_1_fu_90_imgInput_y_466_din;

    imgInput_y_466_write_assign_proc : process(grp_Axi2Mat_1_fu_90_imgInput_y_466_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            imgInput_y_466_write <= grp_Axi2Mat_1_fu_90_imgInput_y_466_write;
        else 
            imgInput_y_466_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_ARADDR <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARADDR;
    m_axi_gmem1_ARBURST <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARBURST;
    m_axi_gmem1_ARCACHE <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARCACHE;
    m_axi_gmem1_ARID <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARID;
    m_axi_gmem1_ARLEN <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARLEN;
    m_axi_gmem1_ARLOCK <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARLOCK;
    m_axi_gmem1_ARPROT <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARPROT;
    m_axi_gmem1_ARQOS <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARQOS;
    m_axi_gmem1_ARREGION <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARREGION;
    m_axi_gmem1_ARSIZE <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARSIZE;
    m_axi_gmem1_ARUSER <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARUSER;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_CS_fsm_state1, grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARVALID, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem1_ARVALID <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_ARVALID;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_CS_fsm_state1, grp_Axi2Mat_1_fu_90_m_axi_gmem1_RREADY, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem1_RREADY <= grp_Axi2Mat_1_fu_90_m_axi_gmem1_RREADY;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv64_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv8_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    srcPtr_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcPtr_blk_n <= srcPtr_empty_n;
        else 
            srcPtr_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcPtr_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcPtr_read <= ap_const_logic_1;
        else 
            srcPtr_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    stride_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, stride_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            stride_blk_n <= stride_empty_n;
        else 
            stride_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stride_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_empty_n, dstMat_1_empty_n, dstMat_2_empty_n, stride_empty_n, dstMat_1_out_full_n, dstMat_2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (dstMat_2_out_full_n = ap_const_logic_0) or (dstMat_1_out_full_n = ap_const_logic_0) or (stride_empty_n = ap_const_logic_0) or (dstMat_2_empty_n = ap_const_logic_0) or (dstMat_1_empty_n = ap_const_logic_0) or (srcPtr_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            stride_read <= ap_const_logic_1;
        else 
            stride_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
